# Generated by Django 4.2.9 on 2024-02-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("phonenumber", models.IntegerField()),
                ("password", models.CharField(max_length=50)),
                ("ifLogged", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "timestamp",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("Paytm", "Paytm"), ("PhonePay", "PhonePay")],
                        max_length=10,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reciever", models.CharField(max_length=255)),
                ("advice", models.CharField(max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
    ]
