# Generated by Django 4.2.9 on 2024-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="user", new_name="ph",
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
