# Generated by Django 4.2.9 on 2024-02-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_user_transaction_ph_alter_user_phonenumber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="ph", new_name="user",
        ),
    ]
