# Generated by Django 4.2.9 on 2024-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_ph_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="username",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
