# Generated by Django 4.2.9 on 2024-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_transaction_all_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="all_messages",
            field=models.CharField(max_length=1000),
        ),
    ]
