# Generated by Django 4.2.9 on 2024-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_reciever_transaction_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="t_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
